version: '3.7'
services:
    mysql-db:
        image: mysql:5.7
        ports:
            - "3306:3306"  
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=${MYSQL_TZ}
        volumes:
            - $PWD/mysql-data:/var/lib/mysql
        networks:
            - netprivate
    
networks:
    netprivate:
